namespace ScholarPath.Infrastructure.Persistence.Seed;

/// <summary>
/// Realistic English + Arabic bodies for the curated <c>KnowledgeDocument</c>
/// (FAQ) rows seeded into the RAG knowledge base. Each pair is hand-written,
/// 300+ words, and uses the same prose voice as the public FAQ. The RAG
/// retriever injects this content as grounding context for the chatbot, so
/// the wording should read like an authoritative answer rather than a
/// marketing blurb.
/// </summary>
internal static class KnowledgeBodies
{
    public const string PlatformFaqEn =
        "ScholarPath is a bilingual scholarship discovery and application platform for students from the Middle East and North Africa who want to study abroad. The platform brings together four kinds of users — students, scholarship-provider companies, independent consultants and platform admins — so the entire scholarship journey, from discovering an opportunity to landing the offer, happens in one place. " +
        "Students sign up for free, complete a short onboarding that captures their academic background, financial situation and target countries, then receive personalised scholarship recommendations. They can save scholarships, track applications across statuses (Researching, In Progress, Submitted, Accepted, Rejected, Waitlisted), upload supporting documents, book paid consultations with verified consultants, and message providers and consultants directly. " +
        "Companies publish and manage scholarship listings, review applications submitted in-app, and access analytics on applicant pipelines. Consultants set their availability, host paid sessions through the integrated meeting room, and publish learning resources to the Resources Hub. Admins moderate the community forum, approve resources before publication, oversee payments and payouts, and manage platform settings. " +
        "All payments inside the platform — consultations and company reviews — flow through Stripe with profit-sharing configured per transaction type. The Resources Hub holds the platform's editorial content: guides, articles, checklists and videos in English and Arabic. The Community forum hosts threaded discussions across more than eight categories. A retrieval-augmented AI assistant answers questions using both the live scholarship catalogue and a curated FAQ knowledge base — the same one this document belongs to. " +
        "If you ever get stuck, the support email is published in the platform settings and the help center links from every page footer.";

    public const string PlatformFaqAr =
        "سكولرباث منصة ثنائية اللغة لاكتشاف المنح الدراسية وتقديم طلباتها، موجهة للطلاب من الشرق الأوسط وشمال أفريقيا الراغبين بالدراسة في الخارج. تجمع المنصة أربعة أنواع من المستخدمين — طلاب، وشركات مانحة للمنح، ومستشارون مستقلون، ومسؤولو منصة — حتى تحدث رحلة المنحة كاملة، من اكتشاف الفرصة إلى الحصول على القبول، في مكان واحد. " +
        "يسجل الطلاب مجاناً، ويُكملون خطوات إعداد قصيرة تجمع خلفيتهم الأكاديمية ووضعهم المالي ودولهم المستهدفة، ثم يحصلون على ترشيحات منح مخصصة. يمكنهم حفظ المنح، وتتبع الطلبات عبر الحالات (بحث، قيد التقديم، مقدمة، مقبول، مرفوض، قائمة انتظار)، ورفع المستندات الداعمة، وحجز استشارات مدفوعة مع مستشارين معتمدين، ومراسلة المانحين والمستشارين مباشرة. " +
        "تنشر الشركات المنح وتديرها، وتراجع الطلبات المقدمة داخل المنصة، وتطّلع على تحليلات لمسار المتقدمين. يحدد المستشارون أوقات توفرهم، ويستضيفون جلسات مدفوعة عبر غرفة الاجتماع المدمجة، وينشرون موارد تعليمية في مركز الموارد. ويُدير المسؤولون منتدى المجتمع، ويوافقون على الموارد قبل النشر، ويشرفون على المدفوعات والتحويلات، ويديرون إعدادات المنصة. " +
        "كل مدفوعات المنصة الداخلية — استشارات ومراجعات شركات — تمر عبر Stripe بنسب مشاركة أرباح محددة لكل نوع معاملة. يحتوي مركز الموارد على محتوى المنصة التحريري: أدلة ومقالات وقوائم تحقق ومقاطع فيديو بالإنجليزية والعربية. ويستضيف منتدى المجتمع نقاشات متفرعة في أكثر من ثماني فئات. ويُجيب مساعد ذكي مُعزَّز بالاسترجاع عن الأسئلة باستخدام كتالوج المنح الحي وقاعدة معرفة أسئلة شائعة منتقاة — وهي القاعدة التي تنتمي إليها هذه الوثيقة. " +
        "إن واجهت أي مشكلة، فبريد الدعم منشور في إعدادات المنصة، ومركز المساعدة يظهر برابط في أسفل كل صفحة.";

    public const string TerminologyEn =
        "Scholarships are described with words that mean different things in different countries — and confusing them costs students money and time. Here is the practical glossary the platform uses. " +
        "A fully funded scholarship covers tuition, accommodation, a monthly stipend, health insurance and usually a one-time travel allowance. The student is expected to cover only minor personal expenses. A partially funded scholarship covers a defined subset — most commonly a tuition waiver of 30%, 50% or 80% — leaving the student to pay the rest plus living costs. " +
        "A tuition waiver reduces or zeroes the published tuition fee but does not include a stipend. A merit scholarship is awarded on academic or extracurricular merit; a need-based scholarship is awarded on demonstrated financial need; a hybrid programme uses both. A bursary, in many countries, is a smaller one-off grant — usually need-based. A fellowship typically refers to graduate-level funding with a research or teaching component, often including a stipend higher than a normal scholarship. " +
        "A grant differs from a scholarship in that it is rarely competitive in the same way: it is awarded once eligibility is met, and is more common for specific projects, research costs or living-cost support. A loan is repayable, even if subsidised — never confuse a loan with a scholarship. A government-sponsored scholarship is funded by the destination country or your home country and usually carries a service obligation: a number of years working in your home country after graduation. " +
        "When you see \"financial aid package\" in an offer letter, read it carefully: the package can stack a partial scholarship, a departmental award, a work-study allowance and a small grant. Add them up before deciding the offer is or is not affordable.";

    public const string TerminologyAr =
        "تُوصف المنح الدراسية بكلمات معناها يختلف بين الدول — والخلط بينها يكلّف الطلاب مالاً ووقتاً. إليك المعجم العملي الذي تستخدمه المنصة. " +
        "المنحة الممولة بالكامل تغطي الرسوم الدراسية والسكن وراتباً شهرياً وتأميناً صحياً وعادةً بدل سفر لمرة واحدة. يُتوقع من الطالب تغطية نفقاته الشخصية البسيطة فقط. أما المنحة الممولة جزئياً فتغطي جزءاً محدداً — غالباً إعفاء من الرسوم بنسبة 30% أو 50% أو 80% — ويدفع الطالب الباقي مع تكاليف المعيشة. " +
        "إعفاء الرسوم يُقلل أو يُلغي الرسوم المعلنة لكنه لا يشمل راتباً. والمنحة الاستحقاقية تُمنح بناءً على التميز الأكاديمي أو خارج الفصل؛ والمنحة القائمة على الحاجة تُمنح بناءً على الحاجة المالية المثبتة؛ والبرنامج الهجين يستخدم كليهما. والمنحة (Bursary) في كثير من الدول، هي منحة لمرة واحدة أصغر — غالباً على أساس الحاجة. والزمالة (Fellowship) عادةً تشير إلى تمويل الدراسات العليا مع مكوّن بحثي أو تدريسي، وغالباً ما تتضمن راتباً أعلى من المنحة العادية. " +
        "والمنحة العامة (Grant) تختلف عن المنحة الدراسية في أنها نادراً ما تكون تنافسية بالطريقة نفسها: تُمنح بمجرد استيفاء الأهلية، وأكثر شيوعاً في مشاريع محددة أو تكاليف بحث أو دعم معيشة. أما القرض فيُسدَّد حتى لو كان مدعوماً — لا تخلط أبداً بين القرض والمنحة. والمنحة الحكومية الممولة من دولة الوجهة أو دولتك عادةً ما يصاحبها التزام خدمة: عدد من السنوات للعمل في بلدك بعد التخرج. " +
        "حين ترى \"حزمة مساعدة مالية\" في خطاب القبول، اقرأها بعناية: قد تجمع الحزمة منحة جزئية وجائزة من القسم وبدل عمل-دراسة ومنحة صغيرة. اجمعها كلها قبل أن تحكم بأن العرض مناسب أو لا.";

    public const string SopWritingEn =
        "A statement of purpose is the single piece of writing that selection panels read most carefully. The strongest statements share the same structure. " +
        "Open with a specific moment, not a general claim. \"I have always loved learning\" is forgettable. \"In my second year, I rebuilt our family bakery's inventory system on weekends — that is when I knew I wanted to study supply chain analytics\" is a paragraph the reviewer remembers. " +
        "After the opening, devote one paragraph to academic preparation: what you studied, why it matters, and one or two concrete achievements. Resist the temptation to list every honour. Pick the two most relevant to the programme you are applying to and explain what they taught you. " +
        "The next paragraph belongs to why this programme, at this institution. Generic praise of a university is a wasted paragraph. Specific reasons — a particular professor's research, a course you read about that does not exist elsewhere, an alumni network in your home country — make the reviewer believe you have done your homework. " +
        "Reserve one paragraph for the future. What will you do during the programme? What problems will you work on? What do you intend to do in the five years afterwards? Reviewers are funding a trajectory, not a CV — show them where their investment leads. " +
        "Close briefly and concretely. Avoid restating the opening. End with a forward-looking sentence that connects your goals to the scholarship's mission. " +
        "Practical limits: 700 to 900 words for most programmes; 500 words if the prompt specifies; never exceed the word limit. Read it aloud at least once. Ask one reader inside your field and one outside it to read and comment.";

    public const string SopWritingAr =
        "خطاب الغرض هو القطعة الكتابية الوحيدة التي تقرأها لجان الاختيار بأكبر عناية. تتشارك أقوى الخطابات في الهيكل نفسه. " +
        "افتح بلحظة محددة، لا بادعاء عام. \"لطالما أحببت التعلم\" جملة سهلة النسيان. أما \"في سنتي الجامعية الثانية، أعدت بناء نظام مخزون مخبز عائلتنا في عطلات الأسبوع — هناك عرفت أنني أريد دراسة تحليلات سلاسل الإمداد\" فهي فقرة يتذكرها المراجع. " +
        "بعد الافتتاحية، اجعل فقرة كاملة للإعداد الأكاديمي: ما درست، ولماذا يهم، وإنجازاً أو إنجازين ملموسَين. قاوم إغراء سرد كل تكريم. اختر الأكثر صلة ببرنامج تقديمك واشرح ما تعلمته منه. " +
        "الفقرة التالية تخص: لماذا هذا البرنامج، في هذه المؤسسة. الإطراء العام على جامعة فقرة مهدورة. الأسباب المحددة — بحث أستاذ معين، مقرر قرأت عنه ولا يوجد في مكان آخر، شبكة خريجين في بلدك — تجعل المراجع يصدّق أنك أنجزت واجبك. " +
        "خصّص فقرة للمستقبل. ماذا ستفعل خلال البرنامج؟ على أي مشاكل ستعمل؟ ما الذي تنوي فعله في السنوات الخمس التالية؟ المراجعون يموّلون مساراً، لا سيرة ذاتية — أرهم إلى أين يقود استثمارهم. " +
        "اختم باختصار وتحديد. تجنب إعادة صياغة الافتتاحية. أنهِ بجملة تطلّعية تربط أهدافك برسالة المنحة. " +
        "حدود عملية: من 700 إلى 900 كلمة لمعظم البرامج؛ 500 كلمة إن نصّت التعليمات على ذلك؛ لا تتجاوز الحد أبداً. اقرأه بصوت مرتفع مرة واحدة على الأقل. واطلب من قارئ من داخل تخصصك وآخر من خارجه أن يقرآه ويعلّقا.";

    public const string RecommendationFaqEn =
        "Recommendation letters are usually the deciding factor between two candidates with similar academic records. They are also the most under-managed part of the application — students assume \"my professor will write whatever they want\" and accept whatever they get. The strongest applicants manage the letter actively. " +
        "Who to ask. Pick people who have observed you doing the thing the scholarship is about. A junior lecturer who saw you lead a class project writes a more credible letter than a famous professor who saw you in a 200-person lecture. Two strong specific letters are better than three vague generic ones. " +
        "When to ask. Six weeks before the earliest deadline is the minimum. Reminder of three weeks, then ten days, then 72 hours is reasonable. Anything closer than three weeks risks a hastily written letter. " +
        "What to send with the request. A short brief makes the writer's job easy: which scholarship, what the deadline is, why you are applying, your CV, a draft of your statement of purpose, and two or three points you hope the letter could touch on — a specific project, a moment when you solved a problem, an interaction the writer remembers. Many writers will lift sentences directly from your brief. That is fine. " +
        "Format and submission. Most scholarships now require the letter to be submitted directly by the writer, often through a secure link. Send your writer the link the moment it is generated. Some scholarships still accept letters on letterhead emailed to a committee inbox — confirm the exact requirement before relying on memory. " +
        "After submission. Thank your writer in writing. When you get an outcome — accepted, rejected, deferred — tell them. Writers remember candidates who close the loop, and they write better letters next time.";

    public const string RecommendationFaqAr =
        "تكون خطابات التوصية عادةً العامل الحاسم بين مرشحَين متشابهَين أكاديمياً. وهي أيضاً الجزء الأقل إدارة في الطلب — يفترض الطلاب أن \"أستاذي سيكتب ما يريد\" ويقبلون ما يحصلون عليه. أقوى المتقدمين يديرون الخطاب بفاعلية. " +
        "ممن تطلب. اختر أشخاصاً شاهدوك تفعل ما تدور حوله المنحة. محاضر مبتدئ شاهدك تقود مشروعاً صفياً يكتب خطاباً أكثر مصداقية من أستاذ مشهور شاهدك في محاضرة من 200 طالب. خطابان قويان محددان أفضل من ثلاثة عامة مبهمة. " +
        "متى تطلب. ستة أسابيع قبل أبكر موعد نهائي هي الحد الأدنى. تذكير قبل ثلاثة أسابيع، ثم قبل عشرة أيام، ثم قبل 72 ساعة أمر معقول. أي وقت أقل من ثلاثة أسابيع يخاطر بكتابة الخطاب على عجل. " +
        "ما ترسله مع الطلب. ملخص قصير يجعل عمل الكاتب سهلاً: أي منحة، ما الموعد النهائي، لماذا تتقدم، سيرتك الذاتية، مسودة خطاب الغرض، ونقطتان أو ثلاث تأمل أن يتطرق إليها الخطاب — مشروع محدد، لحظة حللت فيها مشكلة، تفاعل يتذكره الكاتب. كثير من الكتاب سيستخدمون جملاً من ملخصك حرفياً. لا بأس بذلك. " +
        "الصيغة والتقديم. معظم المنح اليوم تشترط أن يقدم الكاتب الخطاب مباشرة عبر رابط آمن. أرسل إلى كاتبك الرابط فور إصداره. ولا تزال بعض المنح تقبل خطابات على ورق رسمي تُرسل بالبريد الإلكتروني إلى صندوق اللجنة — تأكد من المتطلب الدقيق قبل الاعتماد على الذاكرة. " +
        "بعد التقديم. اشكر كاتبك كتابياً. وعندما تحصل على نتيجة — قُبلت، رُفضت، أُجّلت — أخبره. الكتاب يتذكرون المرشحين الذين يُغلقون الدائرة، ويكتبون خطابات أفضل في المرة التالية.";

    public const string VisaUkEn =
        "The UK Student visa (formerly Tier 4) is required for non-UK nationals studying any course longer than six months. The current rules — accurate at the time of writing — are described below. Always cross-check with the official UKVI site and your university's international office before relying on any single source. " +
        "Eligibility. You need an unconditional offer (a Confirmation of Acceptance for Studies, CAS) from a licensed sponsor, demonstrated English proficiency at the required level, evidence of sufficient funds to cover your first year of tuition plus prescribed living costs (around £1,334 per month inside London and £1,023 outside London), and a clean criminal record. " +
        "The 28-day rule. The funds you show must have been in your named account (or your parent's named account, with a signed declaration) for at least 28 consecutive days before you apply. The closing balance of that period must meet the threshold. Large deposits in the last days look like borrowed funds and are a common rejection reason. " +
        "Application process. The application is submitted online via gov.uk, with biometric data captured at a Visa Application Centre. You will need a tuberculosis certificate if you come from a listed country, an Academic Technology Approval Scheme (ATAS) clearance for some STEM courses, and the immigration health surcharge paid up front (£776 per year for students at the time of writing). " +
        "Processing time and outcome. Decisions inside the published service standard take three weeks for standard applications; priority and super priority services exist for an extra fee. Once approved, you receive a vignette in your passport valid for 90 days, during which you must collect a Biometric Residence Permit (BRP) from a post office in the UK within 10 days of arrival.";

    public const string VisaUkAr =
        "تأشيرة الطالب البريطانية (المعروفة سابقاً بالطبقة الرابعة) مطلوبة لغير حاملي الجنسية البريطانية لدراسة أي برنامج أطول من ستة أشهر. القواعد الحالية — دقيقة وقت الكتابة — موضحة أدناه. تحقق دائماً من موقع UKVI الرسمي ومن مكتب الشؤون الدولية في جامعتك قبل الاعتماد على أي مصدر واحد. " +
        "الأهلية. تحتاج إلى عرض قبول غير مشروط (وثيقة تأكيد القبول للدراسة CAS) من جهة راعية مرخصة، وإثبات إتقان الإنجليزية بالمستوى المطلوب، ودليل على أموال كافية لتغطية رسوم سنتك الأولى وتكاليف المعيشة المقررة (حوالي 1,334 جنيهاً شهرياً داخل لندن و1,023 جنيهاً خارجها)، وسجل جنائي نظيف. " +
        "قاعدة 28 يوماً. الأموال التي تُظهرها يجب أن تكون في حسابك المسجل (أو حساب والدك المسجل، مع إقرار موقع) لمدة 28 يوماً متتالياً على الأقل قبل التقديم. ويجب أن يحقق رصيد إغلاق تلك الفترة الحد الأدنى. الإيداعات الكبيرة في الأيام الأخيرة تبدو كأموال مُقترضة وهي سبب رفض شائع. " +
        "إجراءات التقديم. يُقدَّم الطلب عبر gov.uk، مع التقاط البيانات الحيوية في مركز طلبات التأشيرة. ستحتاج إلى شهادة فحص سل إذا كنت من دولة مدرجة، وموافقة من نظام الموافقة التكنولوجية الأكاديمية ATAS لبعض تخصصات STEM، ودفع رسم التأمين الصحي للهجرة مقدماً (776 جنيهاً سنوياً للطلاب وقت الكتابة). " +
        "وقت المعالجة والنتيجة. القرارات ضمن معيار الخدمة المعلن تأخذ ثلاثة أسابيع للطلبات العادية؛ تتوفر خدمات أولوية وأولوية عاجلة بمقابل إضافي. بعد الموافقة، تحصل على ملصق في جواز سفرك يُعمل به 90 يوماً، خلالها يجب أن تستلم بطاقة الإقامة البيومترية BRP من مكتب بريد في المملكة المتحدة خلال 10 أيام من الوصول.";

    public const string VisaUsEn =
        "The F-1 student visa is the main route for academic study in the United States. The process has two distinct phases — first an I-20 from your university, then the consular interview at a US embassy or consulate. " +
        "Step 1: the I-20. After you accept your offer, your university's international student office issues an I-20 — a form that proves your enrolment and the cost of the programme. You must pay the SEVIS I-901 fee (currently $350) before applying for the visa. Keep the SEVIS payment receipt; the consular officer will ask. " +
        "Step 2: the DS-160 and DS-160 confirmation. Complete the online non-immigrant visa application (DS-160). Every detail must match your passport, your I-20 and your supporting documents. Inconsistencies are a common reason for additional scrutiny. " +
        "Step 3: the interview. Schedule the interview at the US embassy or consulate in your country of residence. Bring originals of: passport, the DS-160 confirmation page, the I-20, the SEVIS fee receipt, the visa fee receipt, the admission letter, financial evidence (bank statements, scholarship award letters, sponsorship documents), and any test scores (SAT, GRE, TOEFL, IELTS) the university accepted. " +
        "Demonstrating non-immigrant intent. F-1 visas are non-immigrant: you must convince the officer you plan to return home after your studies. Family ties, property, future job prospects in your home country, and a clear post-graduation plan all help. \"I have no plans after graduation\" is the answer that most often causes a refusal under section 214(b). " +
        "After approval. Visa-stamped passports are usually returned by courier within one to two weeks. F-1 students can enter the US up to 30 days before the programme start date listed on the I-20.";

    public const string VisaUsAr =
        "تأشيرة F-1 هي المسار الرئيسي للدراسة الأكاديمية في الولايات المتحدة. للعملية مرحلتان متمايزتان — أولاً وثيقة I-20 من جامعتك، ثم مقابلة في سفارة أو قنصلية أمريكية. " +
        "الخطوة 1: وثيقة I-20. بعد قبولك للعرض، يُصدر مكتب الطلاب الدوليين في جامعتك وثيقة I-20 — نموذج يُثبت تسجيلك وتكلفة البرنامج. يجب دفع رسم SEVIS I-901 (حالياً 350 دولاراً) قبل التقدم للتأشيرة. احتفظ بإيصال الدفع؛ سيطلبه ضابط القنصلية. " +
        "الخطوة 2: نموذج DS-160 وتأكيده. أكمل طلب التأشيرة غير المهاجرة عبر الإنترنت (DS-160). يجب أن تتطابق كل تفصيلة مع جواز سفرك ووثيقة I-20 ومستنداتك الداعمة. التناقضات سبب شائع لمزيد من التدقيق. " +
        "الخطوة 3: المقابلة. احجز المقابلة في السفارة أو القنصلية الأمريكية في بلد إقامتك. أحضر أصول: جواز السفر، صفحة تأكيد DS-160، وثيقة I-20، إيصال رسم SEVIS، إيصال رسم التأشيرة، خطاب القبول، الأدلة المالية (كشوف بنكية، خطابات منح، وثائق كفالة)، وأي نتائج اختبارات (SAT، GRE، TOEFL، IELTS) قبلتها الجامعة. " +
        "إثبات النية غير المهاجرة. تأشيرات F-1 غير مهاجرة: عليك إقناع الضابط بأنك تنوي العودة لبلدك بعد الدراسة. الروابط العائلية والممتلكات والفرص الوظيفية المستقبلية في بلدك وخطة واضحة بعد التخرج كلها تساعد. \"لا توجد لدي خطط بعد التخرج\" أكثر إجابة تسبب رفضاً وفق المادة 214(b). " +
        "بعد الموافقة. تُعاد جوازات السفر الممهورة عادةً عبر شركة شحن خلال أسبوع إلى أسبوعين. يمكن لطلاب F-1 دخول الولايات المتحدة قبل 30 يوماً كحد أقصى من تاريخ بداية البرنامج المذكور في I-20.";

    public const string VisaSchengenEn =
        "Schengen student visas cover study in any of the 27 member states; rules are broadly aligned but issued by each country's consulate, so the document set varies by destination. The general framework: a long-stay D-type visa for programmes over 90 days, converted on arrival into a residence permit. " +
        "Common requirements. An acceptance letter from a recognised institution, proof of accommodation, financial evidence (varies by country — Germany requires a blocked account of about €11,904 for 12 months at the time of writing; France requires €615 per month evidenced through scholarship letters or sponsorship; Spain accepts a parent's bank statement), valid health insurance, and a clean criminal record. " +
        "Where to apply. Always at the consulate of your destination country. If you live in a country where the destination does not have a consulate, the rules are specific and worth checking — some countries route Schengen applications through a designated VFS or TLS centre. " +
        "Timing. Most countries open the appointment slot three months before the programme start date. Slot availability for popular destinations like Germany and France can fill within days; apply for the appointment as soon as you accept the offer, even if your documents are not all ready. " +
        "After arrival. A Schengen D-visa is typically valid for 90 days from the date of entry. Within that window you must register with the local town hall or immigration office to obtain your residence permit. The deadline varies by country — Germany within 14 days of arrival, France within 90 days, Italy within 8 working days. Missing the deadline can void your stay rights.";

    public const string VisaSchengenAr =
        "تغطي تأشيرات شنغن الدراسية الدراسة في أي من الدول الـ27 الأعضاء؛ القواعد متقاربة عموماً لكن تصدر عن قنصلية كل دولة، فتختلف مجموعة المستندات حسب الوجهة. الإطار العام: تأشيرة إقامة طويلة من النوع D للبرامج التي تتجاوز 90 يوماً، تتحول عند الوصول إلى تصريح إقامة. " +
        "المتطلبات الشائعة. خطاب قبول من مؤسسة معترف بها، وإثبات السكن، والأدلة المالية (تختلف حسب الدولة — تشترط ألمانيا حساباً محجوزاً بحوالي 11,904 يورو لمدة 12 شهراً وقت الكتابة؛ تشترط فرنسا 615 يورو شهرياً مُثبتة بخطابات منحة أو كفالة؛ تقبل إسبانيا كشف حساب والد)، وتأمين صحي ساري، وسجل جنائي نظيف. " +
        "أين تتقدم. دائماً في قنصلية دولة وجهتك. إذا كنت تقيم في دولة لا توجد فيها قنصلية للوجهة، فالقواعد محددة ومن المفيد التحقق منها — توجّه بعض الدول طلبات شنغن عبر مركز VFS أو TLS معتمد. " +
        "التوقيت. تفتح معظم الدول مواعيد الحجز قبل ثلاثة أشهر من بداية البرنامج. توافر المواعيد لوجهات شعبية كألمانيا وفرنسا قد ينفد خلال أيام؛ احجز الموعد فور قبولك العرض، حتى إن لم تكن مستنداتك جاهزة كلها. " +
        "بعد الوصول. تأشيرة شنغن D عادة سارية 90 يوماً من تاريخ الدخول. خلال تلك النافذة يجب أن تسجل في البلدية المحلية أو مكتب الهجرة للحصول على تصريح الإقامة. تختلف المهلة بين الدول — ألمانيا خلال 14 يوماً، فرنسا خلال 90 يوماً، إيطاليا خلال 8 أيام عمل. تجاوز المهلة قد يُلغي حقك في الإقامة.";

    public const string IeltsPrepEn =
        "Most English-taught Master's programmes require IELTS 6.5 overall, with 6.0 in each section. Top programmes require 7.0 overall with 6.5 in each section. Doctoral programmes commonly require 7.0 or higher. Decide your target band before you book the test. " +
        "Format. The Academic IELTS has four sections: Listening (30 minutes plus 10 minutes transfer time, 40 questions), Reading (60 minutes, 40 questions across three passages), Writing (60 minutes for two tasks) and Speaking (11–14 minutes, three parts, face-to-face with an examiner). Listening, Reading and Writing are done on the same day; Speaking is sometimes scheduled within a week of the main test. " +
        "Eight-week preparation plan. Weeks 1–2: take a baseline mock, identify your weakest section, build a vocabulary set of 250 high-frequency academic words. Weeks 3–5: focused drills on your weakest section, with one full timed mock per week. Weeks 6–7: two full timed mocks per week, with Writing and Speaking marked against the official band descriptors. Week 8: one light mock, rest, identity documents and test centre route confirmed. " +
        "Strategies by section. Listening: predict question types from the format and write quick notes — half of lost marks are misspellings, not mishearings. Reading: skim questions first, then scan the passage; manage time by spending 20 minutes per passage. Writing Task 2 carries more weight than Task 1 — spend 40 minutes there, 20 on Task 1. Speaking: extend answers in Part 1 (two or three sentences), take a breath before Part 3 to organise your point. " +
        "Score validity. IELTS scores are valid for two years from the test date — schedule the test so the results stay valid through the start of your programme.";

    public const string IeltsPrepAr =
        "معظم برامج الماجستير المُدرَّسة بالإنجليزية تتطلب 6.5 إجمالي IELTS، مع 6.0 في كل قسم. البرامج الأفضل تتطلب 7.0 إجمالي مع 6.5 في كل قسم. وبرامج الدكتوراه تتطلب عادة 7.0 أو أعلى. حدد درجتك المستهدفة قبل حجز الاختبار. " +
        "الصيغة. يحتوي IELTS الأكاديمي على أربعة أقسام: الاستماع (30 دقيقة بالإضافة إلى 10 دقائق للنقل، 40 سؤالاً)، القراءة (60 دقيقة، 40 سؤالاً عبر ثلاثة نصوص)، الكتابة (60 دقيقة لمهمتين)، والمحادثة (11 إلى 14 دقيقة، ثلاثة أجزاء، وجهاً لوجه مع ممتحن). يُعقد الاستماع والقراءة والكتابة في اليوم نفسه؛ والمحادثة قد تُحدد خلال أسبوع من الاختبار الرئيسي. " +
        "خطة تحضير لثمانية أسابيع. الأسبوعان 1-2: اختبار قاعدي، تحديد أضعف قسم، بناء مجموعة مفردات من 250 كلمة أكاديمية شائعة. الأسابيع 3-5: تدريبات مركزة على القسم الأضعف، مع اختبار تجريبي كامل بتوقيت أسبوعياً. الأسبوعان 6-7: اختباران تجريبيان كاملان بتوقيت أسبوعياً، مع تصحيح الكتابة والمحادثة وفق وصف الباند الرسمي. الأسبوع 8: اختبار خفيف، راحة، تأكيد وثائق الهوية وطريق مركز الاختبار. " +
        "استراتيجيات قسم-قسم. الاستماع: توقع أنواع الأسئلة من الصيغة ودوّن ملاحظات سريعة — نصف الدرجات المفقودة أخطاء تهجئة لا أخطاء سماع. القراءة: تصفح الأسئلة أولاً ثم امسح النص؛ نظّم الوقت بـ20 دقيقة لكل نص. مهمة الكتابة الثانية أثقل وزناً من الأولى — اقضِ 40 دقيقة عليها و20 على الأولى. المحادثة: مدّد إجاباتك في الجزء الأول (جملتان أو ثلاث)، خذ نفساً قبل الجزء الثالث لتنظيم نقطتك. " +
        "صلاحية الدرجة. درجات IELTS سارية لمدة سنتين من تاريخ الاختبار — حدد موعد اختبارك بحيث تبقى النتائج سارية حتى بداية برنامجك.";

    public const string ToeflPrepEn =
        "Most US universities accept TOEFL iBT as proof of English. The typical Master's requirement is 90 with no section below 22; competitive programmes require 100 with no section below 25. Doctoral programmes commonly require 100 or higher. " +
        "Format. The TOEFL iBT is fully digital, around three hours: Reading (35 minutes, two passages of 10 questions each), Listening (36 minutes, six lectures or conversations), Speaking (16 minutes, four tasks), Writing (29 minutes, two tasks — an integrated task that combines reading, listening and writing, and an academic discussion task). All sections are scored on 0–30, totalling 0–120. " +
        "A 30-day study plan. Days 1–5: baseline mock and a study calendar. Days 6–15: drill the weakest section daily, integrate the others on alternating days. Days 16–25: mix all four sections daily; do one full timed mock at the midpoint. Days 26–28: three full timed mocks on consecutive days, score honestly, list common errors. Days 29–30: no new content, rest, prepare test centre logistics. " +
        "Tactics by section. Reading: skim the passage first, then read questions; do not memorise vocabulary lists — read in context. Listening: take structured notes (main idea, examples, attitude markers); the TOEFL rewards understanding of organisation, not just facts. Speaking: practice the integrated tasks aloud until you can summarise a reading and lecture in 60 seconds. Writing: the integrated task carries equal weight; practise paraphrasing the reading and the lecture into your own academic English. " +
        "Score validity. TOEFL iBT scores are valid for two years from the test date.";

    public const string ToeflPrepAr =
        "تقبل معظم الجامعات الأمريكية TOEFL iBT كإثبات للإنجليزية. الطلب النموذجي لماجستير 90 دون أي قسم أقل من 22؛ البرامج التنافسية تتطلب 100 دون أي قسم أقل من 25. وبرامج الدكتوراه تتطلب عادة 100 أو أعلى. " +
        "الصيغة. TOEFL iBT اختبار رقمي بالكامل، حوالي ثلاث ساعات: القراءة (35 دقيقة، نصان كل منهما 10 أسئلة)، الاستماع (36 دقيقة، ست محاضرات أو محادثات)، المحادثة (16 دقيقة، أربع مهام)، الكتابة (29 دقيقة، مهمتان — مهمة متكاملة تجمع القراءة والاستماع والكتابة، ومهمة نقاش أكاديمي). كل قسم يُقيَّم من 0 إلى 30، بإجمالي 0 إلى 120. " +
        "خطة دراسة لثلاثين يوماً. الأيام 1-5: اختبار قاعدي وجدول دراسة. الأيام 6-15: تدريب يومي على القسم الأضعف، ودمج البقية في أيام متناوبة. الأيام 16-25: خلط الأقسام الأربعة يومياً؛ مع اختبار تجريبي كامل في المنتصف. الأيام 26-28: ثلاثة اختبارات تجريبية كاملة في أيام متتالية، قيّمها بصدق، اكتب الأخطاء الشائعة. اليومان 29-30: لا محتوى جديد، راحة، إعداد لوجستيات مركز الاختبار. " +
        "تكتيكات قسم-قسم. القراءة: تصفح النص أولاً ثم اقرأ الأسئلة؛ لا تحفظ قوائم مفردات — اقرأ في السياق. الاستماع: دوّن ملاحظات منظمة (الفكرة الرئيسية، أمثلة، إشارات الموقف)؛ يكافئ TOEFL فهم التنظيم، لا الحقائق فقط. المحادثة: درّب نفسك على المهام المتكاملة بصوت مرتفع حتى تستطيع تلخيص قراءة ومحاضرة في 60 ثانية. الكتابة: المهمة المتكاملة بوزن متساوٍ؛ درّب نفسك على إعادة صياغة القراءة والمحاضرة بإنجليزيتك الأكاديمية. " +
        "صلاحية الدرجة. درجات TOEFL iBT سارية لمدة سنتين من تاريخ الاختبار.";

    public const string CountryGermanyEn =
        "Germany is one of the most popular destinations for international students because most public universities charge no tuition or a low semester fee, the academic reputation is strong, and Germany allows graduates to stay 18 months after the degree to look for work. " +
        "Fees and funding. Public universities charge a semester contribution of €100–€350 covering administration and a transit pass. A small number of universities — particularly in Baden-Württemberg — charge €1,500 per semester for non-EU students. Private universities charge tuition in the €10,000–€20,000 range. The main scholarship body is DAAD; many other scholarships exist at the state and university level. " +
        "Cost of living. Students need around €11,904 per year (the blocked account requirement), which roughly maps to €850–€1,000 per month including rent. Munich and Frankfurt are significantly more expensive; cities in eastern Germany are noticeably cheaper. " +
        "Admission. Most Master's programmes admit through Uni-Assist for international applicants. Strong programmes are very competitive — apply by mid-March for autumn intake. Language requirement is either German B2 (for German-taught programmes) or IELTS 6.5 / TOEFL 90 for English-taught ones. " +
        "After graduation. Germany's 18-month post-graduation work-search visa is one of the most generous in Europe. After 24 months of qualifying work, you can apply for a permanent residence permit. Bureaucracy is real — register your address (Anmeldung) within 14 days of moving, keep paper copies of every form, and learn enough German to navigate appointments. ";

    public const string CountryGermanyAr =
        "تُعد ألمانيا من أكثر وجهات الطلاب الدوليين شعبية لأن معظم الجامعات العامة لا تفرض رسوماً دراسية أو تفرض رسماً فصلياً منخفضاً، والسمعة الأكاديمية قوية، وتسمح ألمانيا للخريجين بالبقاء 18 شهراً بعد الدرجة للبحث عن عمل. " +
        "الرسوم والتمويل. تفرض الجامعات العامة مساهمة فصلية بين 100 و350 يورو تغطي الإدارة وبطاقة المواصلات. عدد قليل من الجامعات — وخاصة في بادن فورتمبيرغ — تفرض 1,500 يورو فصلياً للطلاب من خارج الاتحاد الأوروبي. الجامعات الخاصة تفرض رسوماً بين 10,000 و20,000 يورو. الجهة المنحية الرئيسية DAAD؛ وتوجد منح أخرى كثيرة على مستوى الولاية والجامعة. " +
        "تكلفة المعيشة. يحتاج الطلاب إلى حوالي 11,904 يورو سنوياً (متطلب الحساب المحجوز)، ما يعادل تقريباً 850 إلى 1,000 يورو شهرياً بما في ذلك الإيجار. ميونيخ وفرانكفورت أغلى بشكل ملحوظ؛ مدن شرق ألمانيا أرخص بوضوح. " +
        "القبول. يتم القبول لمعظم برامج الماجستير عبر Uni-Assist للمتقدمين الدوليين. البرامج القوية تنافسية جداً — تقدم بحلول منتصف مارس لقبول الخريف. متطلب اللغة إما الألمانية بمستوى B2 (للبرامج المُدرَّسة بالألمانية) أو IELTS 6.5 / TOEFL 90 للمُدرَّسة بالإنجليزية. " +
        "بعد التخرج. تأشيرة البحث عن عمل بعد التخرج في ألمانيا لمدة 18 شهراً من الأكثر سخاءً في أوروبا. بعد 24 شهراً من العمل المؤهل، يمكنك التقدم لتصريح إقامة دائم. البيروقراطية حقيقية — سجل عنوانك (Anmeldung) خلال 14 يوماً من الانتقال، واحتفظ بنسخ ورقية من كل نموذج، وتعلم ما يكفي من الألمانية للتعامل مع المواعيد.";

    public const string CountryCanadaEn =
        "Canada attracts international students with strong universities, a clear post-graduation work permit, and a path to permanent residence — but the cost of tuition for non-residents is significant and rising. " +
        "Fees and funding. International undergraduate tuition ranges from CAD 20,000 to CAD 60,000 per year; Master's tuition is CAD 15,000 to CAD 50,000. Funded research-based Master's and PhD programmes are common in STEM and often combine a tuition waiver with a teaching or research stipend. Vanier scholarships (PhD), Banting fellowships (postdoctoral) and Trudeau scholarships are the highest-profile awards. Many provinces and individual universities offer entrance scholarships and waivers. " +
        "Cost of living. Toronto and Vancouver are expensive (CAD 1,800–2,500 per month including rent); Montreal, Halifax and Calgary are more moderate (CAD 1,200–1,700). Health coverage varies by province — Ontario does not cover international students, who must buy private insurance; British Columbia covers students after three months. " +
        "Admission. Most universities admit directly through their own portals, with deadlines from October to early February for September intake. IELTS 6.5 / TOEFL 90 is the common threshold; some programmes also require GRE/GMAT. " +
        "Post-graduation. The Post-Graduation Work Permit (PGWP) allows up to three years of open work authorisation after completing a programme of at least eight months. Two to three years of skilled work plus completion of a Canadian credential is a strong path to permanent residence via Express Entry — the country's main economic immigration stream.";

    public const string CountryCanadaAr =
        "تجذب كندا الطلاب الدوليين بجامعاتها القوية، وتصريح العمل الواضح بعد التخرج، ومسار للإقامة الدائمة — لكن تكلفة الرسوم للطلاب غير المقيمين كبيرة وفي ارتفاع. " +
        "الرسوم والتمويل. تتراوح رسوم البكالوريوس الدولية من 20,000 إلى 60,000 دولار كندي سنوياً؛ ورسوم الماجستير من 15,000 إلى 50,000 دولار كندي. برامج الماجستير والدكتوراه البحثية الممولة شائعة في تخصصات STEM وغالباً ما تجمع إعفاء الرسوم مع راتب تدريس أو بحث. منح Vanier (دكتوراه) وزمالات Banting (ما بعد الدكتوراه) ومنح Trudeau هي الجوائز الأبرز. وتقدم العديد من المقاطعات والجامعات منحاً وإعفاءات للقبول. " +
        "تكلفة المعيشة. تورنتو وفانكوفر مكلفتان (1,800-2,500 دولار كندي شهرياً مع الإيجار)؛ ومونتريال وهاليفاكس وكالغاري معتدلة (1,200-1,700). تختلف التغطية الصحية حسب المقاطعة — أونتاريو لا تغطي الطلاب الدوليين، وعليهم شراء تأمين خاص؛ كولومبيا البريطانية تغطي الطلاب بعد ثلاثة أشهر. " +
        "القبول. معظم الجامعات تقبل مباشرة عبر بوابتها الخاصة، بمواعيد من أكتوبر إلى أوائل فبراير لقبول سبتمبر. IELTS 6.5 / TOEFL 90 هو الحد الشائع؛ بعض البرامج تتطلب أيضاً GRE/GMAT. " +
        "ما بعد التخرج. يسمح تصريح العمل بعد التخرج (PGWP) بثلاث سنوات كحد أقصى من العمل المفتوح بعد إكمال برنامج لا يقل عن ثمانية أشهر. سنتان أو ثلاث من العمل الماهر مع إكمال شهادة كندية مسار قوي إلى الإقامة الدائمة عبر Express Entry — تيار الهجرة الاقتصادية الرئيسي للبلد.";

    public const string CountryUkEn =
        "The UK has the highest concentration of globally ranked universities outside the United States, and the Graduate Route lets international students stay two years after the degree (three years after a PhD) to look for work without a sponsor. " +
        "Fees and funding. International undergraduate tuition typically runs £20,000–£35,000 per year, postgraduate £20,000–£40,000. The most prestigious awards for international students are Chevening (master's), Commonwealth Scholarships (master's and PhD for Commonwealth nationals), and university-specific scholarships like Cambridge's Gates and Oxford's Clarendon. Many universities offer International Excellence scholarships covering 25%–50% of tuition. " +
        "Cost of living. UKVI requires you to evidence £1,334 per month in London and £1,023 outside London — these are minimum thresholds, not realistic budgets. Plan for £1,500 per month in London or £1,100 outside for a single student. " +
        "Admission. Undergraduate applications are centralised through UCAS, with a January deadline. Postgraduate applications are direct to universities, usually open from October to July, but the strongest programmes effectively close by January. The English requirement is IELTS 6.5–7.0 depending on the course; some courses accept TOEFL or Cambridge English exams. " +
        "Post-graduation. The Graduate Route is a non-sponsored two-year work visa that does not require a job offer. After that, sustained skilled employment can lead to a Skilled Worker visa and, eventually, indefinite leave to remain.";

    public const string CountryUkAr =
        "تمتلك المملكة المتحدة أعلى تركيز من الجامعات المصنفة عالمياً خارج الولايات المتحدة، ويتيح مسار التخرج للطلاب الدوليين البقاء سنتين بعد الدرجة (وثلاث سنوات بعد الدكتوراه) للبحث عن عمل دون كفيل. " +
        "الرسوم والتمويل. تتراوح رسوم البكالوريوس الدولية عادة من 20,000 إلى 35,000 جنيه سنوياً، والدراسات العليا من 20,000 إلى 40,000. أبرز الجوائز للطلاب الدوليين منح Chevening (ماجستير)، ومنح الكومنولث (ماجستير ودكتوراه لمواطني الكومنولث)، ومنح خاصة بالجامعات مثل Gates في كامبريدج وClarendon في أكسفورد. وتقدم جامعات كثيرة منح International Excellence تغطي 25%-50% من الرسوم. " +
        "تكلفة المعيشة. تشترط UKVI إثبات 1,334 جنيه شهرياً في لندن و1,023 جنيه خارجها — هذه حدود دنيا لا ميزانيات واقعية. خطط لـ1,500 جنيه شهرياً في لندن أو 1,100 خارجها لطالب أعزب. " +
        "القبول. طلبات البكالوريوس مركزية عبر UCAS، بموعد نهائي في يناير. طلبات الدراسات العليا تذهب مباشرة إلى الجامعات، وعادة تفتح من أكتوبر إلى يوليو، لكن أقوى البرامج تغلق فعلياً بحلول يناير. متطلب الإنجليزية IELTS 6.5-7.0 حسب المقرر؛ بعض المقررات تقبل TOEFL أو امتحانات كامبريدج. " +
        "ما بعد التخرج. مسار التخرج تأشيرة عمل غير مكفولة لسنتين لا تتطلب عرض عمل. بعد ذلك، يمكن أن تقود الوظيفة الماهرة المستدامة إلى تأشيرة العامل الماهر، وفي النهاية إلى الإقامة غير المحددة.";

    public const string CountryUsaEn =
        "The United States combines the largest concentration of top-ranked universities, the broadest range of subjects and the most varied funding models — but also the highest tuition for non-residents and the most complex visa process. " +
        "Fees and funding. Undergraduate tuition at private universities ranges USD 50,000–80,000 per year; public universities charge USD 25,000–45,000 for out-of-state and international students. Master's tuition is similar. PhD students in research disciplines are almost always fully funded — full tuition waiver plus a stipend of USD 25,000–40,000 — in exchange for teaching or research duties. " +
        "Scholarships. The Fulbright programme is the highest-profile scholarship, awarded by partner countries to send students to the US. Many universities offer merit scholarships at the undergraduate level (Vanderbilt, Emory, Washington University). At Master's level, individual departments and external bodies (Aga Khan Foundation, Inlaks Foundation, MasterCard Foundation) are the main funders. " +
        "Cost of living. Highly variable. New York City and the Bay Area run USD 2,000–3,500 per month; college towns in the Midwest are USD 900–1,500. Health insurance is mandatory for F-1 students and is usually billed by the university at USD 2,000–4,500 per year. " +
        "Post-graduation. F-1 students can use Optional Practical Training (OPT) for 12 months after graduation; STEM graduates can extend OPT by 24 months. After OPT, transition to a long-term work visa (typically H-1B) is competitive, with a yearly lottery.";

    public const string CountryUsaAr =
        "تجمع الولايات المتحدة أكبر تركيز من الجامعات الأعلى تصنيفاً، وأوسع نطاق من التخصصات، وأكثر نماذج التمويل تنوعاً — لكنها أيضاً صاحبة أعلى رسوم لغير المقيمين وأكثر عمليات التأشيرة تعقيداً. " +
        "الرسوم والتمويل. رسوم البكالوريوس في الجامعات الخاصة تتراوح بين 50,000 و80,000 دولار سنوياً؛ والجامعات الحكومية تفرض 25,000 إلى 45,000 على الطلاب من خارج الولاية والدوليين. رسوم الماجستير مشابهة. طلاب الدكتوراه في التخصصات البحثية ممولون تمويلاً كاملاً تقريباً دائماً — إعفاء كامل من الرسوم وراتب من 25,000 إلى 40,000 دولار — مقابل واجبات تدريس أو بحث. " +
        "المنح. برنامج Fulbright هو أبرز المنح، تمنحها الدول الشريكة لإرسال طلاب إلى الولايات المتحدة. تقدم جامعات كثيرة منحاً استحقاقية على مستوى البكالوريوس (Vanderbilt، Emory، Washington University). على مستوى الماجستير، الأقسام الفردية والجهات الخارجية (مؤسسة آغا خان، مؤسسة Inlaks، مؤسسة MasterCard) هي الممولون الرئيسيون. " +
        "تكلفة المعيشة. متغيرة جداً. نيويورك ومنطقة الخليج بين 2,000 و3,500 دولار شهرياً؛ مدن الجامعات في الغرب الأوسط بين 900 و1,500. التأمين الصحي إلزامي لطلاب F-1، وتفوتره الجامعة عادة بين 2,000 و4,500 دولار سنوياً. " +
        "ما بعد التخرج. يمكن لطلاب F-1 استخدام التدريب العملي الاختياري (OPT) لمدة 12 شهراً بعد التخرج؛ يمكن لخريجي STEM تمديد OPT بـ24 شهراً. بعد OPT، الانتقال إلى تأشيرة عمل طويلة الأجل (عادة H-1B) تنافسي، بقرعة سنوية.";
}
