// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScholarPath.Infrastructure.Persistence;

#nullable disable

namespace ScholarPath.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260301234110_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnboardingComplete")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_AspNetUsers_Role");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            AccessFailedCount = 0,
                            AccountStatus = "Active",
                            ConcurrencyStamp = "ADMIN-CONCURRENCY-STAMP-00001",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@scholarpath.com",
                            EmailConfirmed = true,
                            FirstName = "System",
                            IsActive = true,
                            IsOnboardingComplete = true,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SCHOLARPATH.COM",
                            NormalizedUserName = "ADMIN@SCHOLARPATH.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBzopFBef9EbyXq08be+PDy9bpasNFbYqmiSYXxvLVk3ydlcbIBNF4KeMFkqu9/OTQ==",
                            PhoneNumberConfirmed = false,
                            Role = "Admin",
                            SecurityStamp = "ADMIN-SECURITY-STAMP-00000001",
                            TwoFactorEnabled = false,
                            UserName = "admin@scholarpath.com"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            AccessFailedCount = 0,
                            AccountStatus = "Active",
                            ConcurrencyStamp = "STUDENT-CONCURRENCY-STAMP-002",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "ahmed.student@scholarpath.com",
                            EmailConfirmed = true,
                            FirstName = "Ahmed",
                            IsActive = true,
                            IsOnboardingComplete = true,
                            LastName = "Hassan",
                            LockoutEnabled = false,
                            NormalizedEmail = "AHMED.STUDENT@SCHOLARPATH.COM",
                            NormalizedUserName = "AHMED.STUDENT@SCHOLARPATH.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENnfSCXEfIvwmiulLqrD69j7vHG3dq+P/5wbiM/k9bbUZWruE2CSXXWvcSqYkj7Niw==",
                            PhoneNumberConfirmed = false,
                            Role = "Student",
                            SecurityStamp = "STUDENT-SECURITY-STAMP-0000002",
                            TwoFactorEnabled = false,
                            UserName = "ahmed.student@scholarpath.com"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            AccessFailedCount = 0,
                            AccountStatus = "Active",
                            ConcurrencyStamp = "CONSULT-CONCURRENCY-STAMP-03",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sara.consultant@scholarpath.com",
                            EmailConfirmed = true,
                            FirstName = "Sara",
                            IsActive = true,
                            IsOnboardingComplete = true,
                            LastName = "Mohamed",
                            LockoutEnabled = false,
                            NormalizedEmail = "SARA.CONSULTANT@SCHOLARPATH.COM",
                            NormalizedUserName = "SARA.CONSULTANT@SCHOLARPATH.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEITdr5Aifj2zBzl4OM+yP6AWgGMc3zPUSFi6HUXZjzY4WXk9/CvMASxZIx8r5cEekg==",
                            PhoneNumberConfirmed = false,
                            Role = "Consultant",
                            SecurityStamp = "CONSULT-SECURITY-STAMP-000003",
                            TwoFactorEnabled = false,
                            UserName = "sara.consultant@scholarpath.com"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            AccessFailedCount = 0,
                            AccountStatus = "Active",
                            ConcurrencyStamp = "COMPANY-CONCURRENCY-STAMP-004",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "omar.company@scholarpath.com",
                            EmailConfirmed = true,
                            FirstName = "Omar",
                            IsActive = true,
                            IsOnboardingComplete = true,
                            LastName = "Khalil",
                            LockoutEnabled = false,
                            NormalizedEmail = "OMAR.COMPANY@SCHOLARPATH.COM",
                            NormalizedUserName = "OMAR.COMPANY@SCHOLARPATH.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPrDShx08aOmDP6z/OLyYXfyF7pvJM1EDbsV9wicesVdlZqTNVN3k/XtUobxDoLQqg==",
                            PhoneNumberConfirmed = false,
                            Role = "Company",
                            SecurityStamp = "COMPANY-SECURITY-STAMP-000004",
                            TwoFactorEnabled = false,
                            UserName = "omar.company@scholarpath.com"
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NameAr")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Categories_Name");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Science, Technology, Engineering, and Mathematics scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§ ÙˆØ§Ù„Ù‡Ù†Ø¯Ø³Ø© ÙˆØ§Ù„Ø±ÙŠØ§Ø¶ÙŠØ§Øª",
                            IsDeleted = false,
                            Name = "STEM",
                            NameAr = "Ø§Ù„Ø¹Ù„ÙˆÙ… ÙˆØ§Ù„ØªÙƒÙ†ÙˆÙ„ÙˆØ¬ÙŠØ§"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Scholarships for arts, literature, history, and philosophy",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„ÙÙ†ÙˆÙ† ÙˆØ§Ù„Ø£Ø¯Ø¨ ÙˆØ§Ù„ØªØ§Ø±ÙŠØ® ÙˆØ§Ù„ÙÙ„Ø³ÙØ©",
                            IsDeleted = false,
                            Name = "Arts & Humanities",
                            NameAr = "Ø§Ù„ÙÙ†ÙˆÙ† ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø¥Ù†Ø³Ø§Ù†ÙŠØ©"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Business administration, finance, and economics scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø£Ø¹Ù…Ø§Ù„ ÙˆØ§Ù„Ù…Ø§Ù„ÙŠØ© ÙˆØ§Ù„Ø§Ù‚ØªØµØ§Ø¯",
                            IsDeleted = false,
                            Name = "Business & Economics",
                            NameAr = "Ø§Ù„Ø£Ø¹Ù…Ø§Ù„ ÙˆØ§Ù„Ø§Ù‚ØªØµØ§Ø¯"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Medical, nursing, pharmacy, and public health scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„Ø·Ø¨ ÙˆØ§Ù„ØªÙ…Ø±ÙŠØ¶ ÙˆØ§Ù„ØµÙŠØ¯Ù„Ø© ÙˆØ§Ù„ØµØ­Ø© Ø§Ù„Ø¹Ø§Ù…Ø©",
                            IsDeleted = false,
                            Name = "Medicine & Health Sciences",
                            NameAr = "Ø§Ù„Ø·Ø¨ ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„ØµØ­ÙŠØ©"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Civil, mechanical, electrical, and software engineering scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„Ù‡Ù†Ø¯Ø³Ø© Ø§Ù„Ù…Ø¯Ù†ÙŠØ© ÙˆØ§Ù„Ù…ÙŠÙƒØ§Ù†ÙŠÙƒÙŠØ© ÙˆØ§Ù„ÙƒÙ‡Ø±Ø¨Ø§Ø¦ÙŠØ© ÙˆÙ‡Ù†Ø¯Ø³Ø© Ø§Ù„Ø¨Ø±Ù…Ø¬ÙŠØ§Øª",
                            IsDeleted = false,
                            Name = "Engineering",
                            NameAr = "Ø§Ù„Ù‡Ù†Ø¯Ø³Ø©"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Legal studies and international law scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³Ø§Øª Ø§Ù„Ù‚Ø§Ù†ÙˆÙ†ÙŠØ© ÙˆØ§Ù„Ù‚Ø§Ù†ÙˆÙ† Ø§Ù„Ø¯ÙˆÙ„ÙŠ",
                            IsDeleted = false,
                            Name = "Law",
                            NameAr = "Ø§Ù„Ù‚Ø§Ù†ÙˆÙ†"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000007"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Teaching, pedagogy, and educational leadership scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø§Ù„ØªØ¯Ø±ÙŠØ³ ÙˆØ§Ù„ØªØ±Ø¨ÙŠØ© ÙˆØ§Ù„Ù‚ÙŠØ§Ø¯Ø© Ø§Ù„ØªØ¹Ù„ÙŠÙ…ÙŠØ©",
                            IsDeleted = false,
                            Name = "Education",
                            NameAr = "Ø§Ù„ØªØ¹Ù„ÙŠÙ…"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000008"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Psychology, sociology, political science, and anthropology scholarships",
                            DescriptionAr = "Ù…Ù†Ø­ Ø¹Ù„Ù… Ø§Ù„Ù†ÙØ³ ÙˆØ§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ ÙˆØ§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø³ÙŠØ§Ø³ÙŠØ© ÙˆØ§Ù„Ø£Ù†Ø«Ø±ÙˆØ¨ÙˆÙ„ÙˆØ¬ÙŠØ§",
                            IsDeleted = false,
                            Name = "Social Sciences",
                            NameAr = "Ø§Ù„Ø¹Ù„ÙˆÙ… Ø§Ù„Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠØ©"
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ParentCommentId");

                    b.HasIndex("PostId")
                        .HasDatabaseName("IX_Comments_PostId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Groups_Name");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "A community for students applying to DAAD scholarships. Share tips, experiences, and support each other through the application process.",
                            DescriptionAr = "Ù…Ø¬ØªÙ…Ø¹ Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ù…ØªÙ‚Ø¯Ù…ÙŠÙ† Ù„Ù…Ù†Ø­ DAAD. Ø´Ø§Ø±ÙƒÙˆØ§ Ø§Ù„Ù†ØµØ§Ø¦Ø­ ÙˆØ§Ù„Ø®Ø¨Ø±Ø§Øª ÙˆØ§Ø¯Ø¹Ù…ÙˆØ§ Ø¨Ø¹Ø¶ÙƒÙ… Ø§Ù„Ø¨Ø¹Ø¶ Ø®Ù„Ø§Ù„ Ø¹Ù…Ù„ÙŠØ© Ø§Ù„ØªÙ‚Ø¯ÙŠÙ….",
                            IsDeleted = false,
                            IsPrivate = false,
                            MaxMembers = 200,
                            Name = "DAAD Scholarship Applicants",
                            NameAr = "Ù…ØªÙ‚Ø¯Ù…Ùˆ Ù…Ù†Ø­Ø© DAAD"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatorId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Everything about studying in the United Kingdom: university selection, visa process, living costs, and scholarship opportunities.",
                            DescriptionAr = "ÙƒÙ„ Ù…Ø§ ÙŠØªØ¹Ù„Ù‚ Ø¨Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙÙŠ Ø§Ù„Ù…Ù…Ù„ÙƒØ© Ø§Ù„Ù…ØªØ­Ø¯Ø©: Ø§Ø®ØªÙŠØ§Ø± Ø§Ù„Ø¬Ø§Ù…Ø¹Ø© ÙˆØ¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„ØªØ£Ø´ÙŠØ±Ø© ÙˆØªÙƒØ§Ù„ÙŠÙ Ø§Ù„Ù…Ø¹ÙŠØ´Ø© ÙˆÙØ±Øµ Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ©.",
                            IsDeleted = false,
                            IsPrivate = false,
                            MaxMembers = 500,
                            Name = "Study in the UK",
                            NameAr = "Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙÙŠ Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ§"
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique()
                        .HasDatabaseName("IX_GroupMembers_UserId_GroupId");

                    b.ToTable("GroupMembers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Role = "Admin",
                            UserId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Role = "Member",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("60000000-0000-0000-0000-000000000002"),
                            Role = "Admin",
                            UserId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("61000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            GroupId = new Guid("60000000-0000-0000-0000-000000000002"),
                            Role = "Member",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Like", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId", "CommentId")
                        .IsUnique()
                        .HasDatabaseName("IX_Likes_UserId_CommentId")
                        .HasFilter("CommentId IS NOT NULL");

                    b.HasIndex("UserId", "PostId")
                        .IsUnique()
                        .HasDatabaseName("IX_Likes_UserId_PostId")
                        .HasFilter("PostId IS NOT NULL");

                    b.ToTable("Likes", t =>
                        {
                            t.HasCheckConstraint("CK_Likes_PostOrComment", "(PostId IS NOT NULL AND CommentId IS NULL) OR (PostId IS NULL AND CommentId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReceiverId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Messages_CreatedAt");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Messages_GroupId");

                    b.HasIndex("ReceiverId")
                        .HasDatabaseName("IX_Messages_ReceiverId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_Messages_SenderId");

                    b.ToTable("Messages", t =>
                        {
                            t.HasCheckConstraint("CK_Messages_ReceiverOrGroup", "(ReceiverId IS NOT NULL AND GroupId IS NULL) OR (ReceiverId IS NULL AND GroupId IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MessageAr")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("RelatedEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RelatedEntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsRead")
                        .HasDatabaseName("IX_Notifications_IsRead");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Notifications_UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "Your account has been activated. Start exploring scholarships and join communities to connect with fellow students.",
                            MessageAr = "ØªÙ… ØªÙØ¹ÙŠÙ„ Ø­Ø³Ø§Ø¨Ùƒ. Ø§Ø¨Ø¯Ø£ ÙÙŠ Ø§Ø³ØªÙƒØ´Ø§Ù Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© ÙˆØ§Ù†Ø¶Ù… Ø¥Ù„Ù‰ Ø§Ù„Ù…Ø¬ØªÙ…Ø¹Ø§Øª Ù„Ù„ØªÙˆØ§ØµÙ„ Ù…Ø¹ Ø²Ù…Ù„Ø§Ø¦Ùƒ Ø§Ù„Ø·Ù„Ø§Ø¨.",
                            Title = "Welcome to ScholarPath!",
                            TitleAr = "Ù…Ø±Ø­Ø¨Ù‹Ø§ Ø¨Ùƒ ÙÙŠ ScholarPath!",
                            Type = "System",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsRead = false,
                            Message = "A new fully-funded scholarship matching your profile has been posted. Check it out before the deadline!",
                            MessageAr = "ØªÙ… Ù†Ø´Ø± Ù…Ù†Ø­Ø© Ù…Ù…ÙˆÙ„Ø© Ø¨Ø§Ù„ÙƒØ§Ù…Ù„ Ø¬Ø¯ÙŠØ¯Ø© ØªØªÙˆØ§ÙÙ‚ Ù…Ø¹ Ù…Ù„ÙÙƒ Ø§Ù„Ø´Ø®ØµÙŠ. ØªØ­Ù‚Ù‚ Ù…Ù†Ù‡Ø§ Ù‚Ø¨Ù„ Ø§Ù„Ù…ÙˆØ¹Ø¯ Ø§Ù„Ù†Ù‡Ø§Ø¦ÙŠ!",
                            RelatedEntityId = new Guid("30000000-0000-0000-0000-000000000001"),
                            RelatedEntityType = "Scholarship",
                            Title = "New Scholarship: DAAD Graduate Scholarship",
                            TitleAr = "Ù…Ù†Ø­Ø© Ø¬Ø¯ÙŠØ¯Ø©: Ù…Ù†Ø­Ø© DAAD Ù„Ù„Ø¯Ø±Ø§Ø³Ø§Øª Ø§Ù„Ø¹Ù„ÙŠØ§",
                            Type = "ScholarshipAlert",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002")
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("IX_Posts_AuthorId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Posts_GroupId");

                    b.HasIndex("GroupId", "CreatedAt")
                        .HasDatabaseName("IX_Posts_GroupId_CreatedAt");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReplacedByToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("IX_RefreshTokens_Token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_RefreshTokens_UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("DescriptionAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Resources");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Category = "Application Tips",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A comprehensive guide covering structure, tone, and common mistakes to avoid when writing scholarship personal statements.",
                            DescriptionAr = "Ø¯Ù„ÙŠÙ„ Ø´Ø§Ù…Ù„ ÙŠØºØ·ÙŠ Ø§Ù„Ù‡ÙŠÙƒÙ„ ÙˆØ§Ù„Ø£Ø³Ù„ÙˆØ¨ ÙˆØ§Ù„Ø£Ø®Ø·Ø§Ø¡ Ø§Ù„Ø´Ø§Ø¦Ø¹Ø© Ø§Ù„ØªÙŠ ÙŠØ¬Ø¨ ØªØ¬Ù†Ø¨Ù‡Ø§ Ø¹Ù†Ø¯ ÙƒØªØ§Ø¨Ø© Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ø´Ø®ØµÙŠØ©.",
                            IsDeleted = false,
                            Title = "How to Write a Winning Scholarship Essay",
                            TitleAr = "ÙƒÙŠÙ ØªÙƒØªØ¨ Ù…Ù‚Ø§Ù„Ø© Ù…Ù†Ø­Ø© Ø¯Ø±Ø§Ø³ÙŠØ© Ù†Ø§Ø¬Ø­Ø©",
                            Type = "Article",
                            Url = "https://scholarpath.com/resources/scholarship-essay-guide"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Category = "Test Preparation",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A 30-day structured study plan for IELTS preparation with practice materials and tips for each section.",
                            DescriptionAr = "Ø®Ø·Ø© Ø¯Ø±Ø§Ø³ÙŠØ© Ù…Ù†Ø¸Ù…Ø© Ù„Ù…Ø¯Ø© 30 ÙŠÙˆÙ…Ù‹Ø§ Ù„Ù„ØªØ­Ø¶ÙŠØ± Ù„Ø§Ù…ØªØ­Ø§Ù† IELTS Ù…Ø¹ Ù…ÙˆØ§Ø¯ ØªØ¯Ø±ÙŠØ¨ÙŠØ© ÙˆÙ†ØµØ§Ø¦Ø­ Ù„ÙƒÙ„ Ù‚Ø³Ù….",
                            IsDeleted = false,
                            Title = "IELTS Preparation: Free Study Plan",
                            TitleAr = "Ø§Ù„ØªØ­Ø¶ÙŠØ± Ù„Ø§Ù…ØªØ­Ø§Ù† IELTS: Ø®Ø·Ø© Ø¯Ø±Ø§Ø³ÙŠØ© Ù…Ø¬Ø§Ù†ÙŠØ©",
                            Type = "Guide",
                            Url = "https://scholarpath.com/resources/ielts-study-plan"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Category = "Scholarship Search",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "A curated list of the best online scholarship search engines and databases specifically useful for students from the Arab region.",
                            DescriptionAr = "Ù‚Ø§Ø¦Ù…Ø© Ù…Ù†Ø³Ù‚Ø© Ù„Ø£ÙØ¶Ù„ Ù…Ø­Ø±ÙƒØ§Øª Ø§Ù„Ø¨Ø­Ø« ÙˆÙ‚ÙˆØ§Ø¹Ø¯ Ø§Ù„Ø¨ÙŠØ§Ù†Ø§Øª Ù„Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© Ø§Ù„Ù…ÙÙŠØ¯Ø© ØªØ­Ø¯ÙŠØ¯Ù‹Ø§ Ù„Ù„Ø·Ù„Ø§Ø¨ Ù…Ù† Ø§Ù„Ù…Ù†Ø·Ù‚Ø© Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©.",
                            IsDeleted = false,
                            Title = "Top 10 Scholarship Databases for Arab Students",
                            TitleAr = "Ø£ÙØ¶Ù„ 10 Ù‚ÙˆØ§Ø¹Ø¯ Ø¨ÙŠØ§Ù†Ø§Øª Ù„Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¹Ø±Ø¨",
                            Type = "Article",
                            Url = "https://scholarpath.com/resources/scholarship-databases"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Category = "Application Tips",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Professional email templates and tips for requesting strong recommendation letters from professors and employers.",
                            DescriptionAr = "Ù‚ÙˆØ§Ù„Ø¨ Ø¨Ø±ÙŠØ¯ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ Ø§Ø­ØªØ±Ø§ÙÙŠØ© ÙˆÙ†ØµØ§Ø¦Ø­ Ù„Ø·Ù„Ø¨ Ø®Ø·Ø§Ø¨Ø§Øª ØªÙˆØµÙŠØ© Ù‚ÙˆÙŠØ© Ù…Ù† Ø§Ù„Ø£Ø³Ø§ØªØ°Ø© ÙˆØ£ØµØ­Ø§Ø¨ Ø§Ù„Ø¹Ù…Ù„.",
                            IsDeleted = false,
                            Title = "Recommendation Letter Request Template",
                            TitleAr = "Ù†Ù…ÙˆØ°Ø¬ Ø·Ù„Ø¨ Ø®Ø·Ø§Ø¨ Ø§Ù„ØªÙˆØµÙŠØ©",
                            Type = "Template",
                            Url = "https://scholarpath.com/resources/recommendation-letter-template"
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.SavedScholarship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScholarshipId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ScholarshipId");

                    b.HasIndex("UserId", "ScholarshipId")
                        .IsUnique()
                        .HasDatabaseName("IX_SavedScholarships_UserId_ScholarshipId");

                    b.ToTable("SavedScholarships");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Scholarship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AwardAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("DegreeLevel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EligibilityDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EligibleCountries")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EligibleMajors")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FundingType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal?>("MinGPA")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("OfficialLink")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequiredDocuments")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_Scholarships_Country");

                    b.HasIndex("Deadline")
                        .HasDatabaseName("IX_Scholarships_Deadline");

                    b.HasIndex("DegreeLevel")
                        .HasDatabaseName("IX_Scholarships_DegreeLevel");

                    b.HasIndex("FieldOfStudy")
                        .HasDatabaseName("IX_Scholarships_FieldOfStudy");

                    b.HasIndex("FundingType")
                        .HasDatabaseName("IX_Scholarships_FundingType");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Scholarships_IsActive");

                    b.ToTable("Scholarships");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            AwardAmount = 1200m,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Country = "Germany",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            Deadline = new DateTime(2026, 10, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DegreeLevel = "Masters",
                            Description = "The German Academic Exchange Service (DAAD) offers fully funded scholarships for international students pursuing Master's or PhD degrees in Germany. The scholarship covers tuition, monthly stipend, health insurance, and travel costs.",
                            DescriptionAr = "ØªÙ‚Ø¯Ù… Ù‡ÙŠØ¦Ø© Ø§Ù„ØªØ¨Ø§Ø¯Ù„ Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠ Ø§Ù„Ø£Ù„Ù…Ø§Ù†ÙŠØ© (DAAD) Ù…Ù†Ø­Ù‹Ø§ Ù…Ù…ÙˆÙ„Ø© Ø¨Ø§Ù„ÙƒØ§Ù…Ù„ Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¯ÙˆÙ„ÙŠÙŠÙ† Ù„Ù…ØªØ§Ø¨Ø¹Ø© Ø¯Ø±Ø¬Ø© Ø§Ù„Ù…Ø§Ø¬Ø³ØªÙŠØ± Ø£Ùˆ Ø§Ù„Ø¯ÙƒØªÙˆØ±Ø§Ù‡ ÙÙŠ Ø£Ù„Ù…Ø§Ù†ÙŠØ§. ØªØºØ·ÙŠ Ø§Ù„Ù…Ù†Ø­Ø© Ø§Ù„Ø±Ø³ÙˆÙ… Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© ÙˆØ§Ù„Ø±Ø§ØªØ¨ Ø§Ù„Ø´Ù‡Ø±ÙŠ ÙˆØ§Ù„ØªØ£Ù…ÙŠÙ† Ø§Ù„ØµØ­ÙŠ ÙˆØªÙƒØ§Ù„ÙŠÙ Ø§Ù„Ø³ÙØ±.",
                            EligibilityDescription = "Open to graduates from developing countries with excellent academic records. Applicants must hold a Bachelor's degree and have at least 2 years of work experience.",
                            EligibleCountries = "[\"Egypt\",\"Jordan\",\"Morocco\",\"Tunisia\",\"Lebanon\"]",
                            EligibleMajors = "[\"Computer Science\",\"Engineering\",\"Natural Sciences\",\"Mathematics\"]",
                            FieldOfStudy = "All Fields",
                            FundingType = "FullyFunded",
                            IsActive = true,
                            IsDeleted = false,
                            MinGPA = 3.0m,
                            OfficialLink = "https://www.daad.de/en/study-and-research-in-germany/scholarships/",
                            RequiredDocuments = "CV, motivation letter, academic transcripts, recommendation letters, language certificate",
                            Title = "DAAD Graduate Scholarship",
                            TitleAr = "Ù…Ù†Ø­Ø© DAAD Ù„Ù„Ø¯Ø±Ø§Ø³Ø§Øª Ø§Ù„Ø¹Ù„ÙŠØ§"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            AwardAmount = 18000m,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Country = "United Kingdom",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "GBP",
                            Deadline = new DateTime(2026, 11, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DegreeLevel = "Masters",
                            Description = "Chevening is the UK government's international awards programme offering fully funded Master's degrees at any UK university. It provides a unique opportunity for future leaders and decision-makers.",
                            DescriptionAr = "ØªØ´ÙŠÙÙ†ÙŠÙ†Ø¬ Ù‡Ùˆ Ø¨Ø±Ù†Ø§Ù…Ø¬ Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯ÙˆÙ„ÙŠ Ù„Ù„Ø­ÙƒÙˆÙ…Ø© Ø§Ù„Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ© Ø§Ù„Ø°ÙŠ ÙŠÙ‚Ø¯Ù… Ø¯Ø±Ø¬Ø§Øª Ù…Ø§Ø¬Ø³ØªÙŠØ± Ù…Ù…ÙˆÙ„Ø© Ø¨Ø§Ù„ÙƒØ§Ù…Ù„ ÙÙŠ Ø£ÙŠ Ø¬Ø§Ù…Ø¹Ø© Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ©. ÙŠÙˆÙØ± ÙØ±ØµØ© ÙØ±ÙŠØ¯Ø© Ù„Ù„Ù‚Ø§Ø¯Ø© ÙˆØµÙ†Ø§Ø¹ Ø§Ù„Ù‚Ø±Ø§Ø± Ø§Ù„Ù…Ø³ØªÙ‚Ø¨Ù„ÙŠÙŠÙ†.",
                            EligibilityDescription = "Applicants must have at least 2 years of work experience, hold an undergraduate degree, and return to their home country for at least 2 years after the scholarship.",
                            EligibleCountries = "[\"Egypt\",\"Jordan\",\"Iraq\",\"Saudi Arabia\",\"UAE\"]",
                            FieldOfStudy = "All Fields",
                            FundingType = "FullyFunded",
                            IsActive = true,
                            IsDeleted = false,
                            MinGPA = 3.0m,
                            OfficialLink = "https://www.chevening.org/",
                            RequiredDocuments = "Personal statement, reference letters, academic transcripts, English language test",
                            Title = "Chevening Scholarship",
                            TitleAr = "Ù…Ù†Ø­Ø© ØªØ´ÙŠÙÙ†ÙŠÙ†Ø¬"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            AwardAmount = 800m,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000007"),
                            Country = "Turkey",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "TRY",
                            Deadline = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            DegreeLevel = "Bachelors",
                            Description = "The Turkish Government offers fully funded scholarships for international students at all academic levels. The program includes Turkish language preparation, tuition waiver, monthly stipend, accommodation, and health insurance.",
                            DescriptionAr = "ØªÙ‚Ø¯Ù… Ø§Ù„Ø­ÙƒÙˆÙ…Ø© Ø§Ù„ØªØ±ÙƒÙŠØ© Ù…Ù†Ø­Ù‹Ø§ Ù…Ù…ÙˆÙ„Ø© Ø¨Ø§Ù„ÙƒØ§Ù…Ù„ Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¯ÙˆÙ„ÙŠÙŠÙ† ÙÙŠ Ø¬Ù…ÙŠØ¹ Ø§Ù„Ù…Ø±Ø§Ø­Ù„ Ø§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠØ©. ÙŠØ´Ù…Ù„ Ø§Ù„Ø¨Ø±Ù†Ø§Ù…Ø¬ Ø¥Ø¹Ø¯Ø§Ø¯ Ø§Ù„Ù„ØºØ© Ø§Ù„ØªØ±ÙƒÙŠØ© ÙˆØ§Ù„Ø¥Ø¹ÙØ§Ø¡ Ù…Ù† Ø§Ù„Ø±Ø³ÙˆÙ… ÙˆØ§Ù„Ø±Ø§ØªØ¨ Ø§Ù„Ø´Ù‡Ø±ÙŠ ÙˆØ§Ù„Ø³ÙƒÙ† ÙˆØ§Ù„ØªØ£Ù…ÙŠÙ† Ø§Ù„ØµØ­ÙŠ.",
                            EligibilityDescription = "Open to citizens of all countries except Turkey. Undergraduate applicants must be under 21, Master's under 30, and PhD under 35.",
                            EligibleCountries = "[\"Egypt\",\"Palestine\",\"Syria\",\"Yemen\",\"Somalia\"]",
                            FieldOfStudy = "All Fields",
                            FundingType = "FullyFunded",
                            IsActive = true,
                            IsDeleted = false,
                            MaxAge = 21,
                            OfficialLink = "https://www.turkiyeburslari.gov.tr/",
                            RequiredDocuments = "National ID, photo, high school diploma, transcripts, language certificate (optional)",
                            Title = "Turkish Government Scholarship (Turkiye Burslari)",
                            TitleAr = "Ø§Ù„Ù…Ù†Ø­Ø© Ø§Ù„ØªØ±ÙƒÙŠØ© Ø§Ù„Ø­ÙƒÙˆÙ…ÙŠØ©"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            AwardAmount = 35000m,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000008"),
                            Country = "United States",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Deadline = new DateTime(2026, 5, 31, 0, 0, 0, 0, DateTimeKind.Utc),
                            DegreeLevel = "Masters",
                            Description = "The Fulbright Program provides grants for graduate students to study, conduct research, or teach English in the United States. It is one of the most prestigious scholarship programs in the world.",
                            DescriptionAr = "ÙŠÙ‚Ø¯Ù… Ø¨Ø±Ù†Ø§Ù…Ø¬ ÙÙˆÙ„Ø¨Ø±Ø§ÙŠØª Ù…Ù†Ø­Ù‹Ø§ Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¯Ø±Ø§Ø³Ø§Øª Ø§Ù„Ø¹Ù„ÙŠØ§ Ù„Ù„Ø¯Ø±Ø§Ø³Ø© Ø£Ùˆ Ø¥Ø¬Ø±Ø§Ø¡ Ø§Ù„Ø¨Ø­ÙˆØ« Ø£Ùˆ ØªØ¯Ø±ÙŠØ³ Ø§Ù„Ù„ØºØ© Ø§Ù„Ø¥Ù†Ø¬Ù„ÙŠØ²ÙŠØ© ÙÙŠ Ø§Ù„ÙˆÙ„Ø§ÙŠØ§Øª Ø§Ù„Ù…ØªØ­Ø¯Ø©. ÙˆÙ‡Ùˆ ÙˆØ§Ø­Ø¯ Ù…Ù† Ø£ÙƒØ«Ø± Ø¨Ø±Ø§Ù…Ø¬ Ø§Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© Ø§Ù„Ù…Ø±Ù…ÙˆÙ‚Ø© ÙÙŠ Ø§Ù„Ø¹Ø§Ù„Ù….",
                            EligibilityDescription = "Candidates must hold a Bachelor's degree, demonstrate English proficiency, and have a strong academic and professional record.",
                            EligibleCountries = "[\"Egypt\",\"Lebanon\",\"Jordan\",\"Morocco\",\"Tunisia\",\"Iraq\"]",
                            EligibleMajors = "[\"Public Policy\",\"Engineering\",\"Sciences\",\"Education\",\"Arts\"]",
                            FieldOfStudy = "All Fields",
                            FundingType = "FullyFunded",
                            IsActive = true,
                            IsDeleted = false,
                            MinGPA = 3.0m,
                            OfficialLink = "https://foreign.fulbrightonline.org/",
                            RequiredDocuments = "Application form, personal statement, study plan, recommendation letters, TOEFL/IELTS score",
                            Title = "Fulbright Foreign Student Program",
                            TitleAr = "Ø¨Ø±Ù†Ø§Ù…Ø¬ ÙÙˆÙ„Ø¨Ø±Ø§ÙŠØª Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø£Ø¬Ø§Ù†Ø¨"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000005"),
                            AwardAmount = 25000m,
                            CategoryId = new Guid("20000000-0000-0000-0000-000000000005"),
                            Country = "European Union",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "EUR",
                            Deadline = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            DegreeLevel = "Masters",
                            Description = "Erasmus Mundus Joint Master Degrees are prestigious integrated study programmes delivered by international consortia of higher education institutions. Students study in at least two different European countries.",
                            DescriptionAr = "Ø¯Ø±Ø¬Ø§Øª Ù…Ø§Ø¬Ø³ØªÙŠØ± Ø¥ÙŠØ±Ø§Ø³Ù…ÙˆØ³ Ù…ÙˆÙ†Ø¯ÙˆØ³ Ø§Ù„Ù…Ø´ØªØ±ÙƒØ© Ù‡ÙŠ Ø¨Ø±Ø§Ù…Ø¬ Ø¯Ø±Ø§Ø³ÙŠØ© Ù…ØªÙƒØ§Ù…Ù„Ø© Ù…Ø±Ù…ÙˆÙ‚Ø© ØªÙ‚Ø¯Ù…Ù‡Ø§ Ø§ØªØ­Ø§Ø¯Ø§Øª Ø¯ÙˆÙ„ÙŠØ© Ù„Ù…Ø¤Ø³Ø³Ø§Øª Ø§Ù„ØªØ¹Ù„ÙŠÙ… Ø§Ù„Ø¹Ø§Ù„ÙŠ. ÙŠØ¯Ø±Ø³ Ø§Ù„Ø·Ù„Ø§Ø¨ ÙÙŠ Ø¯ÙˆÙ„ØªÙŠÙ† Ø£ÙˆØ±ÙˆØ¨ÙŠØªÙŠÙ† Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„.",
                            EligibilityDescription = "Open to students and scholars worldwide. Applicants must hold a recognized Bachelor's degree. Partner country applicants receive higher funding.",
                            EligibleCountries = "[\"Egypt\",\"Algeria\",\"Libya\",\"Sudan\",\"Mauritania\"]",
                            EligibleMajors = "[\"Environmental Science\",\"Public Health\",\"Data Science\",\"Urban Planning\"]",
                            FieldOfStudy = "Multiple Fields",
                            FundingType = "FullyFunded",
                            IsActive = true,
                            IsDeleted = false,
                            MinGPA = 3.2m,
                            OfficialLink = "https://erasmus-plus.ec.europa.eu/",
                            RequiredDocuments = "Online application, academic transcripts, CV, motivation letter, language proficiency proof, recommendation letters",
                            Title = "Erasmus Mundus Joint Masters",
                            TitleAr = "Ù…Ù†Ø­ Ø¥ÙŠØ±Ø§Ø³Ù…ÙˆØ³ Ù…ÙˆÙ†Ø¯ÙˆØ³ Ù„Ù„Ù…Ø§Ø¬Ø³ØªÙŠØ± Ø§Ù„Ù…Ø´ØªØ±Ùƒ"
                        });
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.SuccessStory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsApproved")
                        .HasDatabaseName("IX_SuccessStories_IsApproved");

                    b.HasIndex("UserId");

                    b.ToTable("SuccessStories");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.UpgradeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdminNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ExpertiseTags")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Languages")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LinkedInUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PortfolioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProofDocumentUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RequestedRole")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_UpgradeRequests_Status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_UpgradeRequests_UserId");

                    b.ToTable("UpgradeRequests");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Bio")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldOfStudy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("GPA")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<string>("Interests")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TargetCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_UserProfiles_UserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Bio = "Passionate computer science student seeking international scholarship opportunities.",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FieldOfStudy = "Computer Science",
                            GPA = 3.75m,
                            Interests = "[\"AI\",\"Machine Learning\",\"Web Development\"]",
                            TargetCountry = "Germany",
                            UserId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Bio = "Experienced scholarship consultant with 10+ years helping students secure funding.",
                            Country = "Egypt",
                            CreatedAt = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FieldOfStudy = "International Education",
                            UserId = new Guid("10000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholarPath.Domain.Entities.Comment", "ParentComment")
                        .WithMany("Replies")
                        .HasForeignKey("ParentCommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholarPath.Domain.Entities.Post", "Post")
                        .WithMany("Comments")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("ParentComment");

                    b.Navigation("Post");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Group", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Like", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.Comment", "Comment")
                        .WithMany("Likes")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholarPath.Domain.Entities.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Message", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.Group", "Group")
                        .WithMany("Messages")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Notification", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Post", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholarPath.Domain.Entities.Group", "Group")
                        .WithMany("Posts")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.SavedScholarship", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.Scholarship", "Scholarship")
                        .WithMany("SavedScholarships")
                        .HasForeignKey("ScholarshipId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany("SavedScholarships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Scholarship");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Scholarship", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.Category", "Category")
                        .WithMany("Scholarships")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.SuccessStory", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.UpgradeRequest", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithMany("UpgradeRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.UserProfile", b =>
                {
                    b.HasOne("ScholarPath.Domain.Entities.ApplicationUser", "User")
                        .WithOne("UserProfile")
                        .HasForeignKey("ScholarPath.Domain.Entities.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.ApplicationUser", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("RefreshTokens");

                    b.Navigation("SavedScholarships");

                    b.Navigation("UpgradeRequests");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Category", b =>
                {
                    b.Navigation("Scholarships");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Comment", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");

                    b.Navigation("Posts");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Post", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Likes");
                });

            modelBuilder.Entity("ScholarPath.Domain.Entities.Scholarship", b =>
                {
                    b.Navigation("SavedScholarships");
                });
#pragma warning restore 612, 618
        }
    }
}
